### ISSUE TITLE
Fails to build with php-5.5

### ISSUE THREAD

**Issue by vgoodvin** [aterrien/forp-PHP-profiler#21]
OS: Ubuntu 13.10 x86_64
PHP Version: 5.5.3-1ubuntu2.1

```
$ make
/bin/bash /tmp/forp/libtool --mode=compile cc  -I. -I/tmp/forp -DPHP_ATOM_INC -I/tmp/forp/include -I/tmp/forp/main -I/tmp/forp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/forp/php_forp.c -o php_forp.lo 
libtool: compile:  cc -I. -I/tmp/forp -DPHP_ATOM_INC -I/tmp/forp/include -I/tmp/forp/main -I/tmp/forp -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/forp/php_forp.c  -fPIC -DPIC -o .libs/php_forp.o
/tmp/forp/php_forp.c: In function 'zm_deactivate_forp':
/tmp/forp/php_forp.c:202:26: error: lvalue required as left operand of assignment
             zend_execute = old_execute;
                          ^
/tmp/forp/php_forp.c:205:35: warning: assignment from incompatible pointer type [enabled by default]
             zend_execute_internal = old_execute_internal;
                                   ^
make: *** [php_forp.lo] Error 1
```
